name: zad2lab10
on: workflow_dispatch
jobs:
  dockerCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
      - name: Buildx setup
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        id: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Docker build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          platforms: linux/arm64/v8,linux/amd64
          file: ./Dockerfile
          push: true
          tags: scoutertf2/zad2:${{ github.sha }}
          cache-from: type=registry,ref=scoutertf2/zad2:${{ github.sha }}
          cache-to: type=inline

  kubernetesCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
        with:
          repository: scoutertf2/fullstack-zad2-config
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: |
          git config user.name w-sarnowski
          git config user.email sarnowskiwojtek5500@gmial.com
          sed -i -E "s/[0-9a-f]{40}/${{ github.sha }}/g" Deployment.yaml
          git add .
          git commit -m "workflow"
          git push
  